sudo: required
language: ruby

before_install: 
  - "gem install bundler"
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libpcap-dev tcpdump
  - "bundle install"

script: "rake"

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

addons:
  code_climate:
    repo_token: eec82658aa00b89a55bf625517ad267826051f4bb5355b6cb98e6df93b79d1ce
